ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - argon2
  - bcrypt
  - less
  - msgpackr-extract
  - nx
  - prisma
  - sharp
  - unrs-resolver
