// libs/api-common/src/error-codes/error-codes.const.ts
export const ErrorCodes = {
  // Общие ошибки
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  HTTP_ERROR: "HTTP_ERROR",

  // Auth ошибки
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  MISSING_TOKEN: "MISSING_TOKEN",
  INVALID_AUTH_SCHEME: "INVALID_AUTH_SCHEME",
  INVALID_TOKEN: "INVALID_TOKEN",

  // Изображения
  HEIC_CONVERSION_FAILED: "HEIC_CONVERSION_FAILED",
  IMAGE_INVALID_FORMAT: "IMAGE_INVALID_FORMAT",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",

  // Файлы
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  MISSING_FILE: "MISSING_FILE",

  // Пользователи
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // Регистрация
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  DUPLICATE_VALUE: "DUPLICATE_VALUE",
} as const;
